### ISSUE TITLE
Surge demo is not working 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-checkbox#115]
### Please verify the version of auro-checkbox you have installed

@latest

### Please describe the bug

1. Go to http://alaskaairlines-auro-checkbox-dsande-updatedeps.surge.sh/demo
2. see that resources are not loaded in the DOM

<img width="319" alt="Screen Shot 2023-10-09 at 8 52 30 PM" src="https://github.com/AlaskaAirlines/auro-checkbox/assets/181089/50c567fb-c3ce-41fd-8c46-a9fd5f9557d4">

### Reproducing the error

This issue cannot be reproduced on the Auro docsite

### Expected behavior

Resources are updated for the demo release in Surge as expected. 

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Exit criteria

This issue can be closed once the Surge demo is illustrating the auro-checkbox UI as expected.

**Comment by fajar-apri-alaska** [comment]
Could we update the entry point imports here:
https://github.com/AlaskaAirlines/auro-checkbox/blob/8daa3b88cb3d15341dffcb75594fb9e4580c5b3b/index.js#L1-L2

by adding .js extension in the end ?
```
import { AuroCheckbox } from './src/auro-checkbox.js'; 
import { AuroCheckboxGroup } from './src/auro-checkbox-group.js'; 
```
