### ISSUE TITLE
focus-visible code is missing

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-checkbox#127]
### Please verify the version of auro-checkbox you have installed

@latest

### Please describe the bug

1. Go to https://auro.alaskaair.com/components/auro/checkbox
2. Tab through the UI
3. See error

Notice that you are not seeing any UI feedback from tabbing onto any of the check box items. 

### Reproducing the error

This issue is reproducible on the Auro docsite

### Expected behavior

All interactive elements should support `:focus-visible` as an accessible interactive affordance on the element. 

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Additional context

It appears that with a large CSS refactor the `.focus-visible` selector was deleted versus being refactored to support the `:focus-visible` pseudo selector. 

https://github.com/AlaskaAirlines/auro-checkbox/pull/114/files#diff-f1b002481f489a1e54abd539b444b29f9b5f909946f4fe17344c5a266a0ff6d1

### Exit criteria

This issue can be closed once the checkbox element illustrates the proper UI feedback when tabbing to the element on a page.

**Comment by jordanjones243** [comment]
Re-opening this ticket, as the change in the v3.0 was incorrect:
- https://github.com/AlaskaAirlines/auro-checkbox/pull/130/files#diff-f1b002481f489a1e54abd539b444b29f9b5f909946f4fe17344c5a266a0ff6d1R34-R50

The change should involve the `focus-visible` selector, not `focus-within`

**Comment by jason-capsule42** [comment]
This was fixed as part of the theme work.
