### ISSUE TITLE
Input event does not fire in IE11

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/auro-checkbox#2]
## Describe the bug
In IE11, triggering the checkbox does not fire an input event. This prevents the consumer from knowing when the input updates (e.g. a controlled component in React).

## To Reproduce
1. Render the following markup:
```html
<auro-checkbox-group required>
	<span slot="legend">Group label</span>
	<auro-checkbox 
		id="cbx1"
		name="cbxDemo"
		value="yes"
		checked>
		Yes
	</auro-checkbox>
</auro-checkbox-group>
```
2. Add an input event listener to the element
```js
document.querySelector('auro-checkbox').addEventListener('input', function() { console.log('input') });
```
3. Render in IE. Nothing is logged to the console. 

## Expected behavior
The input event is triggered in IE when the checkbox is updated.

## Environment
 - OS: Windows 10
 - Browser: IE11

## Additional context
It seems like IE11 [does not fire input events for checkboxes](https://stackoverflow.com/a/56458172) (I think this bit us before with ods-inputoptions). However, adding an event listener on change did not trigger either.

We need a consistent event to fire cross-browser to be able to respond to user input.

**Comment by blackfalcon** [comment]
We have a few problems here.

1. the test you are using will not work in IE as even IE9 + does not fully support `input` events because Microsoft hates the world 
1. lit element does not support the use of `change` events without creating a custom change event

There is a fix in the works.

**Comment by blackfalcon** [comment]
Updated this issue from BUG to FEATURE. There is not a bug in the existing code, but a new feature is being added to support an outdated spec on a legacy browser.
