### ISSUE TITLE
auro-checkbox: handling for auro-hyperlink behavior inside the text slot

### ISSUE THREAD

**Issue by rallyb13** [AlaskaAirlines/auro-checkbox#25]
## Is your feature request related to a problem? Please describe.
We (NFP) have a checkbox for terms & conditions, which includes a pair of auro-hyperlinks to membership & website terms:
![Screen Shot 2021-06-09 at 11 46 27 AM](https://user-images.githubusercontent.com/9616716/121411389-6b358600-c918-11eb-9e29-c9b035344d9e.png)
When an auro-hyperlink is nested inside an auro-checkbox like this, we have two problems:
First, we have to do special handling to make sure that a click on the hyperlink doesn't also check the box (since it's an external link, the user would not see that the checkbox is changing).
Second, when tabbing through the page, the focus-visible turns makes the whole text block the same color as the default hyperlink.
![Screen Shot 2021-06-09 at 9 33 17 AM](https://user-images.githubusercontent.com/9616716/121411694-c4051e80-c918-11eb-80fa-24f832e7623f.png)
![Screen Shot 2021-06-09 at 9 33 23 AM](https://user-images.githubusercontent.com/9616716/121411696-c49db500-c918-11eb-877a-42975257b212.png)

## Describe the solution you'd like
- On click, the auro-hyperlink would accept the click, and then propagation would be stopped so that the checkbox is not also checked. (Not sure if this should be optional.)
- When auro-checkbox is tabbed over, hyperlinks automatically switch to `ondark` _or an even better contrast color_ since `ondark` is still (as Miles Davis would say) Kind of Blue:
![Screen Shot 2021-06-09 at 11 53 19 AM](https://user-images.githubusercontent.com/9616716/121412285-61605280-c919-11eb-9250-9ef3a05d562d.png)

## Describe alternatives you've considered
- We are currently able to stop propagation in a click handler. ✅ 
- We could do something similar to flip to `ondark`. 😬 
- Direct CSS override of the hyperlink when focus-visible is set is very tricky for my use case as I have the extra complication of React's shadow-DOM. 😭 

**Note:**
I wasn't sure whether to open this in auro-checkbox for automatic handling of content inside or auro-hyperlink.

**Comment by blackfalcon** [comment]
Please see my response to https://github.com/AlaskaAirlines/auro-hyperlink/issues/63 as this directly applies.

**Comment by blackfalcon** [comment]
See https://github.com/AlaskaAirlines/auro-hyperlink/issues/63 for reasons to close this issue.

**Comment by MattSidor** [comment]
Just for future reference, a possible workaround to this is to use the `onInput` event instead of `onClick`. The hyperlinks do not seem to trigger the checkbox when I use that event.
