### ISSUE TITLE
Unable to select checkbox with mouse in IE11

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/auro-checkbox#3]
## Describe the bug
In IE11, clicking on the checkbox does not select/unselect it. Tabbing with the keyboard works as expected.

## To Reproduce
1. Render the following markup:
```html
<auro-checkbox-group required>
	<span slot="legend">Group label</span>
	<auro-checkbox 
		id="cbx1"
		name="cbxDemo"
		value="yes"
		checked>
		Yes
	</auro-checkbox>
</auro-checkbox-group>
```
2. Click on the checkbox. The checkbox is not updated.

## Expected behavior
I can click on the checkbox to check/uncheck it in IE11.

## Environment
 - OS: Windows 10
 - Browser: IE11

Test was done with the Svelte framework, but I don't think that would have introduced any issues.

## Additional context
This [ods-inputoptions issue](https://github.com/AlaskaAirlines/ods-inputoptions/issues/16) seems related.

**Comment by blackfalcon** [comment]
The priority level has been removed. We are in the process of deprecating all support for IE11 except for special use cases. If at such time we have dropped all IE11 support and this issue has not yet been resolved, it will be closed with a `no fix`.
