### ISSUE TITLE
v2.0-rc

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-checkbox#35]
## NEXT MAJOR release 

The following items are to be included with the next MAJOR release of the Auro WC-Generator, all PRs are to be from the feature branch to `v2.0-rc` branch.

- [ ] https://github.com/AlaskaAirlines/auro-checkbox/issues/6
- [ ] https://github.com/AlaskaAirlines/auro-checkbox/issues/40
- [x] #41 
- [ ] https://github.com/AlaskaAirlines/auro-checkbox/issues/47

**Comment by braven112** [comment]
Closing the RC in favor on using the milestone
