### ISSUE TITLE
Checked style hides checkbox in IE11

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/auro-checkbox#4]
## Describe the bug
The keyboard focus style when the checkbox is checked hides the checkbox in IE11 (see screenshot).

## To Reproduce
1. Render the following markup in IE11
```html
<auro-checkbox-group required>
	<span slot="legend">Group label</span>
	<auro-checkbox 
		use:listen
		id="cbx1"
		name="cbxDemo"
		value="yes"
		checked>
		Yes
	</auro-checkbox>
</auro-checkbox-group>
```
2. Tab to the checkbox. Notice that the checkbox disappears and you can't see that the checkbox is checked.

## Expected behavior
I can see that the checkbox is checked when I tab to it in IE11.

## Screenshots
Checked focus style:
![image](https://user-images.githubusercontent.com/4992896/86150958-f5436080-bab2-11ea-808b-ffc49d1132cf.png)

Unchecked focus style (not an issue):
![image](https://user-images.githubusercontent.com/4992896/86151202-481d1800-bab3-11ea-9753-054fc93ce728.png)

## Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: IE11

## Additional context
This seems slightly more significant since [you can't select the checkbox with the mouse](https://github.com/AlaskaAirlines/auro-checkbox/issues/3). Tabbing is the only option.

I believe the problem is due to the use of the focus-within selector, which is [not supported in IE11](https://caniuse.com/#feat=css-focus-within). [I submitted a PR fixing a similar issue](https://github.com/AlaskaAirlines/ods-inputoptions/pull/5) for ods-inputoptions.

**Comment by blackfalcon** [comment]
The priority level has been removed. We are in the process of deprecating all support for IE11 except for special use cases. If at such time we have dropped all IE11 support and this issue has not yet been resolved, it will be closed with a `no fix`.
