### ISSUE TITLE
Create blueprint figma file

### ISSUE THREAD

**Issue by leeejune** [AlaskaAirlines/auro-checkbox#41]
# General Support Request
The auro-checkbox requires a blueprint supporting document to be released to Figma.

## Support request
Review the current state of the auro-checkbox design and create the Figma blueprint document.

## Possible Solution
Design to review current UI for new design opportunities.

## Exit Criteria

- [x]  complete blueprint work
- [x] signoff from Auro engineering
- [x]  add link completed version of auro-checkbox blueprint ([Link](https://www.figma.com/file/wU5lxm5roZpGkm6Af5w8a9/Checkbox?node-id=322%3A298))

**Comment by blackfalcon** [comment]
@leeejune this looks great! Let's go with adding the markdown docs to this repo and updating the docsite.

**Comment by blackfalcon** [comment]
@braven112 the commit for this will be `docs` and will not create a version release. There is no need to bind this to a RC. I'd recommend that it is merged into `main` and then we can update the docsite.
