### ISSUE TITLE
auro-checkbox: unable to programatically uncheck box after user has checked it

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/auro-checkbox#42]
## Describe the bug
After the user has checked an auro-checkbox, you cannot uncheck it with JS, e.g. `document.querySelector('auro-checkbox').checked = false;`.

Related: https://github.com/AlaskaAirlines/auro-radio/issues/30

## To Reproduce
1. Render an auro-checkbox, e.g. `<auro-checkbox id="computers01" name="checkboxDemo2" value="computers">Computers</auro-checkbox>`
2. Check the checkbox using your mouse
3. Attempt to uncheck it programatically, e.g. by selecting it in the inspector and doing `$0.checked = false`
4. The checkbox does not update

## Expected behavior
The checkbox updates based on the property.

## Additional context
The fix might be as simple as changing `?checked="${this.checked}"` to `.checked="${this.checked}"` so that the property is updated instead of the attribute.

The solution to a similar auro-radio issue was more involved because the radio-group needed to control the checked state, but I don't think that's necessary for a checkbox group.

**Comment by geoffrich** [comment]
@blackfalcon @braven112 I didn't add this to the board because I wasn't sure which of the three boards I should add it to.

If folks agree with my proposed fix I can get a PR in today. This came up as part of contact tracing work so I'd like to get a fix out ASAP if possible.

**Comment by blackfalcon** [comment]
@geoffrich there is no need for you to add it to a board, we can take care of that. 

If you feel confident in your approach, from which I don't disagree, then dev it, test it, PR it and we will ship it!
