### ISSUE TITLE
Appears translucent in prod, needs to be filled with white

### ISSUE THREAD

**Issue by KaylaBlyton1** [AlaskaAirlines/auro-checkbox#44]
## Describe the bug
Auro-checkbox appears filled with white in designer files, but shows as translucent in prod. This means if a a background is grey, the inside of the checkbox will also appear grey - which appears as disabled to users. 

## To Reproduce
This error was found it flight stages, but its not in production. Its part of the microsite. Screenshots are below. 

## Expected behavior
Checkboxes should be filled with white for better visibility and clarity.

## Screenshots

![How it should look - filled](https://user-images.githubusercontent.com/83242595/140230046-12196171-3111-46db-971b-6febb31ea619.png)
![How it looks - transparent](https://user-images.githubusercontent.com/83242595/140230062-7ba5a4e5-d8c1-4b3c-9d3b-fb94075f1ec4.png)

**Comment by braven112** [comment]
@KaylaBlyton1 @leeejune When a checkbox is in a disabled state what color should the background be? Still white or do we have a light grey color to use for that situation?

**Comment by KaylaBlyton1** [comment]
@braven112 Here is the blueprint (stealing from @leeejune!)

It looks like the box should be filled with "background/lightest" (aka white) in active, error, and disabled states. 

https://www.figma.com/file/wU5lxm5roZpGkm6Af5w8a9/Checkbox?node-id=322%3A298

**Comment by blackfalcon** [comment]
@braven112 I'd suggest just releasing this as a bug. The blueprint is pretty clear as to what is missing.

**Comment by braven112** [comment]
@blackfalcon That totally works for me.  I created an RC but just to include this bug and the blueprint work.  Are you suggesting that the RC's shouldn't include bugs or blueprint work and we can list those separately on the board?  If so that sounds great to me.

**Comment by KaylaBlyton1** [comment]
@blackfalcon - Thank you for making this update!
