### ISSUE TITLE
Disabled border color

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-checkbox#46]
## Describe the bug

It appears that the disabled border color is the same as the primary state border color. 

<img width="571" alt="Screen Shot 2021-11-07 at 12 24 07 PM" src="https://user-images.githubusercontent.com/181089/140660871-4764c43a-ff09-4889-bec9-fbe252f2909f.png">
<img width="483" alt="Screen Shot 2021-11-07 at 12 24 14 PM" src="https://user-images.githubusercontent.com/181089/140660874-9c44a1b2-ca07-4eb7-9bd9-b0f6eace6982.png">

## To Reproduce

1. Go to http://auro.alaskaair.com/components/auro/checkbox
1. Inslect on the shadow DOM of auro-checkbox
1. See error

## Expected behavior

There is no expected behavior, but this seems incorrect. We should review past design specs to find out of the auro CE is out of spec with the initial design.

**Comment by leeejune** [comment]
https://www.figma.com/file/wU5lxm5roZpGkm6Af5w8a9/Checkbox?node-id=322%3A298
Changes made to the blueprint. The stroke of a disabled checkbox is now "auro-color-border-disabled-on-light"

**Comment by blackfalcon** [comment]
@leeejune thanks. I will make the CSS updates shortly. Is it on your list to create the Figma/Release notes for this page?

**Comment by blackfalcon** [comment]
Yup... https://github.com/AlaskaAirlines/auro-checkbox/issues/41
