### ISSUE TITLE
auro-checkbox: add hover state

### ISSUE THREAD

**Issue by leeejune** [AlaskaAirlines/auro-checkbox#53]
## Is your feature request related to a problem? Please describe.
The checkbox lacks affordance and is not consistent with the new radio button hover interaction. https://github.com/AlaskaAirlines/auro-radio/issues/67

## Describe the solution you'd like
Add a hover state design spec to the blueprint of checkbox and add it as a feature. Also add a gloved hand for the cursor on hover.

**Comment by jdeeezzy** [comment]
New hover, focused, hover selected, focused selected and focused hover states are done. Currently updating blueprint.

**Comment by jdeeezzy** [comment]
Blueprint updated.

**Comment by leeejune** [comment]
Will be done in issue #87
