### ISSUE TITLE
auro-checkbox-group: Hide "(optional)" label

### ISSUE THREAD

**Issue by jordanchang** [AlaskaAirlines/auro-checkbox#59]
## Is your feature request related to a problem? Please describe.
I would like display a checkbox group that is optional to the user, but not include the "(optional)" label in the header.

## Describe the solution you'd like
Don't include "(optional)" at all.  Text displayed should be exactly the text set in the Legend slot.

## Describe alternatives you've considered
We are currently setting required attribute to hide this label.

**Comment by blackfalcon** [comment]
I have to ask, what is the use case for an optional field to appear as required? If you are using `required`, why is that not working?

**Comment by jordanchang** [comment]
Below is a mockup of the use case. 

As a user, I want to select 0 or 1 or more passengers for a food item. The required attribute would work in our case, but just feels odd to mark it required, when it's really not required to proceed.

![image](https://user-images.githubusercontent.com/3304352/173109964-0c0bd860-dd46-401e-baad-ab169c226aa6.png)

**Comment by blackfalcon** [comment]
If the items are silently optional and a user clicks `select` without an option, what is the expectation?

**Comment by jordanchang** [comment]
Forgot to mention this UI is shown as a modal. If no passengers are selected, then the modal closes and no passengers have selected a Cheese Platter.

**Comment by blackfalcon** [comment]
I feel like we are trying to retcon a weird UI interaction. By making this optional, the user can click a button that carries no value and does not produce a positive outcome. 

I'd argue that the button should be disabled until a selection has been made and making a selection prior to hitting the `select` button is required in this micro form UI.

**Comment by jordanchang** [comment]
Good point. But how would you implement unselect? All 3 guests has selected a cheese plate prior (all checked). Shortly after, they now don't want any of the cheese plates (uncheck all).

**Comment by blackfalcon** [comment]
The disabled button is tied to change, not checked/unchecked. So if all people were checked on render, the button would be disabled and any change to those options would enable the button for submission of changed data.

**Comment by jordanchang** [comment]
Correct, the primary CTA button disabling/enabling is a great idea. But the fact remains the checkbox-group has 0 boxes checked and that is still a valid choice implies the group is an optional field. I'm actually OK with the "alternative" as posted at the top of this thread, but wanted to check if there was a more semantically correct way to do this.

**Comment by blackfalcon** [comment]
@jordanchang there really isn't a right/wrong answer to this. Common patterns across the internet support what I have been proposing, but there are also other opinions. 

Given the discussion, I'd argue that this is a better conversation to have with your UX designer and @leeejune to determine if there is a proposed update to move forward on. 

FWIW... we do have a similar feature with input, but there are different use cases there where the text data needs to be validated server-side, so while it is a required field, there is an option to disable the client-side validation.
