### ISSUE TITLE
auro-checkbox: doesn't render on docsite.

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-checkbox#95]
## Describe the bug
When viewing the checkbox examples, the page doesn't render the checkbox

## To Reproduce
1. Go to '[auro.alaskaair.com](https://auro.alaskaair.com/components/auro/checkbox)'
1. See error of component not rendering

## Expected behavior
For the component to show up.

## Screenshots
![image](https://github.com/AlaskaAirlines/auro-checkbox/assets/5118118/6b0c2450-167e-45d5-a9da-398573a5c7dc)

## Additional context
I don't see any relevant console errors

**Comment by Patrick-Daly-AA** [comment]
This is expected to be fixed as we update the repo to current.

**Comment by jordanjones243** [comment]
This issue is being re-opened due to the fact that the latest PR/release is having issues publishing.

**Comment by jordanjones243** [comment]
Issue being re-opened, as there is still an issue with auro-checkbox examples displaying on the docsite.

**Comment by jordanjones243** [comment]
This issue is a docsite bug and the work will be transferred to this ticket: https://github.com/AlaskaAirlines/AuroDocsSite/issues/142
