### ISSUE TITLE
auro-checkbox: add support for CSS parts

### ISSUE THREAD

**Issue by ethanwmiller** [AlaskaAirlines/auro-checkbox#96]
## Is your feature request related to a problem? Please describe.
I would like to manually set the `line-height` property of checkbox label text. My team has a multi-line checkbox label which ends up looking like a paragraph, but the line height is larger than regular text. My team's designer requested that I fix the line height to be consistent with the auro default line height for body text, but I am unable to override the line height being set here: https://github.com/AlaskaAirlines/auro-checkbox/blob/f4998a059dcc118ad8aec0276c304b824c0b073f/src/auro-checkbox.scss#LL96C37-L96C37

## Describe the solution you'd like
An officially supported way to customize the CSS of this component, e.g. through [CSS Parts](https://developer.mozilla.org/en-US/docs/Web/CSS/::part) as mentioned by @jason-capsule42 

## Describe alternatives you've considered
I've attempted to override the styles manually in my React code with no success so far.

## Additional context
I'm told that implementing CSS parts support for the checkbox component is already planned eventually, but it was suggested that I make a ticket to help prioritize the effort. 

Let me know if I can clarify anything or provide more details. Thanks!

**Comment by jordanjones243** [comment]
This issue is being re-opened due to the fact that the latest PR/release is having issues publishing.
